# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# This is your PRODUCTION app configuration

client_id = "43cf7f8681dbe81a1af612979e4049b6"
name = "Goossens Product Exporter"
application_url = "https://YOUR_PRODUCTION_URL_HERE"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  # [[webhooks.subscriptions]]
  # topics = [ "app/uninstalled" ]
  # uri = "/webhooks/app/uninstalled"

  # [[webhooks.subscriptions]]
  # topics = [ "app/scopes_update" ]
  # uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://YOUR_PRODUCTION_URL_HERE/api/auth" ]
